### ISSUE TITLE
Fresh install gives "invalid section token [menalto2piwigo]"

### ISSUE THREAD

**Issue by romanf** [plegall/menalto2piwigo#15]
Hi,
I just installed piwigo and wanted to use the plugin menalto2piwio. The plugin installs correctly but when I try to open it from the admin panel, the error

invalid section token [menalto2piwigo]

is shown.
System is Apache, PHP 7.1, MySQL. Any other info required?

Thanks
Roman

**Comment by Iva83** [comment]
Having the same issue. PHP 5.6, the rest is the same. Trying to ditch Gallery2 for good and looking forward to Piwigo.

**Comment by plegall** [comment]
Will be solved with Piwigo 2.8.6, see https://github.com/Piwigo/Piwigo/issues/602

**Comment by romanf** [comment]
Ah, yes, if you add 0-9 to the regex then it works again. :)

**Comment by ramack** [comment]
should be closed, as Piwigo/Piwigo#602 is also, shouldn't ti?
